### ISSUE TITLE
Can not run on ios, please help

### ISSUE THREAD

**Issue by LanchaBasualdo** [httpswift/swifter#118]
I have a fresh copy of the repositry but each time I try to install i to my iphone with ios9.2 this erros appear:
<img width="254" alt="screen shot 2016-03-25 at 7 30 11 pm" src="https://cloud.githubusercontent.com/assets/12802164/14055371/274b1092-f2c0-11e5-86a0-92452dc398a4.png">

**Comment by glock45** [comment]
hi 

it's because of this commit: https://github.com/httpswift/swifter/commit/45c427434210bd461835825f1ab0c7573ef0c0c5

we try to keep the master branch up to date with the latest builds from https://swift.org/download/#snapshots

to fix the issue you can choose between:
1. a switch to the older version of Swifter - https://github.com/httpswift/swifter/releases/tag/1.1.3
2. upgrade your toolchain to XCODE 7.3 ( with swift tools from March 24, 2016 - https://swift.org/download/#snapshots )

please visit out slack channel for live support

best
